### ISSUE TITLE
Adding custom fields in conf.ini

### ISSUE THREAD

**Issue by leonardol** [blockchain-certificates/cert-tools#24]
Hi.
I've uncommented the line:

`# additional_global_fields = {"fields": [{"path": "$.certificate.subtitle","value": "kim custom subtitle"}]}` 

in conf.ini.

So I've run the script: 

`create-certificate-template -c conf.ini`

the error is:

path is not valid! : certificate.subtitle
Traceback (most recent call last):
  File "/Users/leonardol/anaconda3/bin/create-certificate-template", line 11, in <module>
    sys.exit(main())
  File "/Users/leonardol/anaconda3/lib/python3.6/site-packages/cert_tools/create_v2_certificate_template.py", line 186, in main
    template = create_certificate_template(conf)
  File "/Users/leonardol/anaconda3/lib/python3.6/site-packages/cert_tools/create_v2_certificate_template.py", line 131, in create_certificate_template
    assertion = jsonpath_helpers.set_field(assertion, field['path'], field['value'])
  File "/Users/leonardol/anaconda3/lib/python3.6/site-packages/cert_tools/jsonpath_helpers.py", line 85, in set_field
    raise (Exception(msg))
Exception: path is not valid! : certificate.subtitle

Changing that line removing `.subtitle`:

`additional_global_fields = {"fields": [{"path": "$.certificate","value": "kim custom subtitle"}]}`

all was ok with the following result:

Writing template to /Users/leonardol/cert-tools/sample_data/certificate_templates/test.json
Created template!

Could you help me?

Thanks in advance.

**Comment by leonardol** [comment]
Hi.
I was wrong with the issue I opened. Now I'm aware that the function that adds a custom field, with its value, in the JSON template, could do it only if its parent node exists.
I regret this mistake.
