### ISSUE TITLE
AttributeError: 'str' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by chidoman321** [blockchain-certificates/cert-tools#48]
hi, i followed the cert-tools readme guide, but when i try to run this script instantiate-certificate-batch -c conf.ini, it returns me this err 

(venv) C:\Users\yeyei\OneDrive\Documentos\cert-tools\certs>instantiate-certificate-batch -c conf.ini
Traceback (most recent call last):
  File "c:\users\yeyei\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\yeyei\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\yeyei\OneDrive\Documentos\cert-tools\certs\venv\Scripts\instantiate-certificate-batch.exe\__main__.py", line 7, in <module>
  File "c:\users\yeyei\onedrive\documentos\cert-tools\certs\venv\lib\site-packages\cert_tools\instantiate_v2_certificate_batch.py", line 150, in main
    instantiate_batch(conf)
  File "c:\users\yeyei\onedrive\documentos\cert-tools\certs\venv\lib\site-packages\cert_tools\instantiate_v2_certificate_batch.py", line 114, in instantiate_batch
    certs = create_unsigned_certificates_from_roster(template, recipients, use_identities, config.additional_per_recipient_fields, config.hash_emails)
  File "c:\users\yeyei\onedrive\documentos\cert-tools\certs\venv\lib\site-packages\cert_tools\instantiate_v2_certificate_batch.py", line 73, in create_unsigned_certificates_from_roster
    issued_on = helpers.create_iso8601_tz()
  File "c:\users\yeyei\onedrive\documentos\cert-tools\certs\venv\lib\site-packages\cert_tools\helpers.py", line 61, in create_iso8601_tz
    return ret.isoformat()
AttributeError: 'str' object has no attribute 'isoformat'
![image](https://user-images.githubusercontent.com/49621062/113744059-f81a5400-96c9-11eb-85bb-2bb91af86930.png)

**Comment by chidoman321** [comment]
okey i applied the changes of the failed pull request 

def create_iso8601_tz():
    ret = datetime.now(timezone.utc).isoformat()[:-13]+'Z'
    return ret.isoformat() 
    ret = datetime.now(timezone.utc).isoformat()
    return ret

**Comment by flachica** [comment]
This Issue must be opened. Still happening. I suggest [this](https://github.com/blockchain-certificates/cert-tools/pull/49) PR

**Comment by neon-ninja** [comment]
Looks to have been caused by this commit - https://github.com/blockchain-certificates/cert-tools/commit/c62e355bff68c79db6e0ead3a31a2fefb849c378#diff-c2c850a56d3ef345cce593373b5331dfa854a8826501a7f61586f86404c7e62f

**Comment by parkerqueen** [comment]
The issue still persists. Any update on this?

**Comment by JoshueG** [comment]
Still happening
