### ISSUE TITLE
nonce is a required property

### ISSUE THREAD

**Issue by sreenumalae** [blockchain-certificates/cert-tools#60]
While using the following command to create unsigned certificates using cert-tools

 instantiate-certificate-batch -c conf.ini

.local/lib/python3.8/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
ERROR:root:'nonce' is a required property

On instance:
    {'@context': ['https://www.w3.org/2018/credentials/v1',
                  'https://w3id.org/blockcerts/v3'],
     'credentialSubject': {'alumniOf': {'id': 'https://www.issuer.org'},
                           'id': 'ecdsa-koblitz-pubkey:mtr98kany9G1XYNU74pRnfBQmaCg2FZLmc'},
     'id': 'urn:uuid:6946b7e6-e933-46ea-8950-38d2fc675869',
     'issuanceDate': '2024-06-24T09:59:42Z',
     'issuer': 'https://www.blockcerts.org/samples/2.0/issuer-testnet.json',
     'type': ['VerifiableCredential', 'BlockcertsCredential']}
Traceback (most recent call last):
  File "/home/azureuser/.local/lib/python3.8/site-packages/cert_schema/schema_validator.py", line 102, in validate_json
    jsonschema.validate(certificate_json, schema_json)
  File "/home/azureuser/.local/lib/python3.8/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: 'nonce' is a required property

@lemoustachiste

**Comment by sreenumalae** [comment]
To solve the above issue 
Update the following function create_v3_assertion in cert_tools/create_v3_certificate_template.py
 
`def create_v3_assertion(config):
    ContextUrlsInstance = ContextUrls()
    res = ''.join(random.choices(string.ascii_uppercase +
                             string.digits, k=10))
    assertion = {
        '@context': [
            ContextUrlsInstance.verifiable_credential(),
            ContextUrlsInstance.v3_canonical()
        ],
        'type': ["VerifiableCredential", "BlockcertsCredential"],
        "issuer": config.issuer_id,
        'issuanceDate': '*|DATE|*',
        'id': helpers.URN_UUID_PREFIX + '*|CERTUID|*',
        'nonce' : res
    }
    return assertion
`

**Comment by sreenumalae** [comment]
Instead of Modifying code add nonce in the additional fields

additional_global_fields = {“fields”: [{“path”: “$.nonce”,“value”: “sec:nonce”}]}
